// apps/angular-frontend/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'myworkspace-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-frontend';
}

<header class="flex">
  <img
    alt="Nx logo"
    width="75"
    src="https://nx.dev/assets/images/nx-logo-white.svg"
  />
  <h1>Welcome to {{ title }}!</h1>
</header>
<main>
  <h2>Resources &amp; Tools</h2>
  <p>Thank you for using and showing some ♥ for Nx.</p>
  
  <my-component first="David" middle="Rocha" last="Akmeida"></my-component>
</main>

<router-outlet></router-outlet>

// apps/frontend/src/app/app.tsx
import React from 'react';

import styles from './app.module.scss';

import { ReactComponent as Logo } from './logo.svg';
import star from './star.svg';
import { MyComponent } from '@myworkspace/design-system-react';

export function App() {
  return (
    <div className={styles.app}>
      <header className="flex">
        <Logo width="75" height="75" />
        <h1>Welcome to frontend!</h1>
      </header>
      <main>
        <MyComponent first="David" last="Rock" />
      </main>
    </div>
  );
}

export default App;
